name: MacOS.

on:
  push:
    paths-ignore:
      - '**.md'
      - 'changelog.txt'
      - 'LEGAL'
      - 'LICENSE'
      - '.clang-*'
      - '.gitignore'
      - '.github/**'
      - '!.github/workflows/mac.yml'
      - 'lib/xdg/**'
      - 'snap/**'
      - 'docs/**'
      - 'flatpak/**'
      - 'vcpkg.json'
      - 'vcpkg-*.json'
      - 'src/base/platform/win/**'
      - 'src/base/platform/linux/**'
    branches: [ "develop" ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ develop, develop-macos ]

jobs:

  macos:
    name: MacOS
    runs-on: macos-12

    strategy:
      matrix:
        defines:
          - ""
    env:
      UPLOAD_ARTIFACT: "false"
      ONLY_CACHE: "false"

    steps:
      - name: Get repository name.
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Clone.
        uses: actions/checkout@v2
        with:
          submodules: recursive
          path: ${{ env.REPO_NAME }}

      - name: First set up.
        run: |
          sudo chown -R `whoami`:admin /usr/local/share
          brew install automake

          # Disable spotlight.
          sudo mdutil -a -i off

          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Libraries cache.
        id: cache-libs
        uses: actions/cache@v2
        with:
          path: Libraries
          key: ${{ runner.OS }}-libs-${{ hashFiles(format('{0}/{1}', env.REPO_NAME, env.PREPARE_PATH)) }}
          restore-keys: ${{ runner.OS }}-libs-

      - name: Libraries.
        run: |
          ./$REPO_NAME/build-script/prepare-mac.sh

      - name: Free up some disk space.
        run: |
          cd Libraries
          find . -iname "*.dir" -exec rm -rf {} || true \;

      - name: Build ok-gloox
        run: |
          git clone https://github.com/okstar-org/ok-gloox.git
          cd ok-gloox
          cmake -B out -DCMAKE_BUILD_TYPE=Release
          cmake --build out --config Release
          cmake --install out --config Release

      - name: Build ok-rtc
        run: |
          git clone https://github.com/okstar-org/ok-rtc.git
          cd ok-rtc
          git submodule update --init
          export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig:/usr/local/opt/mozjpeg/lib/pkgconfig:/usr/local/opt/ffmpeg@5/lib/pkgconfig"
          cmake -B out -DCMAKE_BUILD_TYPE=Debug \
          -DJPEG_LIBRARY=/usr/local/opt/mozjpeg/lib \
          -DJPEF_INCLUDE_DIR=/usr/local/opt/mozjpeg/include
          cmake --build out --config=Debug